FROM python:3.10

COPY ./requirements.txt /tmp/requirements.txt

RUN pip3 install --upgrade pip

RUN pip install -r /tmp/requirements.txt

COPY ./ /app

WORKDIR /app

EXPOSE 8000

CMD uvicorn app.main:app --host 0.0.0.0 --port 8000
