"""add new election status for trustee

Revision ID: 0d90832250b7
Revises: 7c8d6769571e
Create Date: 2024-11-26 15:48:40.977363

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '0d90832250b7'
down_revision = '7c8d6769571e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    old_status = sa.Enum('setting_up', 'started', 'ended', 'tally_computed', 'decryptions_uploaded', 'decryptions_combined', 'results_released', name='electionstatusenum')
    old_status.drop(op.get_bind(), checkfirst=False)

    # Enum 'NewStatus'
    new_status = sa.Enum('setting_up', 'started', 'ended', 'ready_key_generation', 'ready_opening', 'computing_tally', 'tally_computed', 'decryptions_uploaded', 'decryptions_combined', 'results_released', name='electionstatusenum')
    new_status.create(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###

    with op.batch_alter_table('psifos_election', schema=None) as batch_op:
        batch_op.alter_column('election_status', type_=new_status, existing_type=old_status)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    new_status = sa.Enum('setting_up', 'started', 'ready_key_generation', 'ready_opening', 'ended', 'tally_computed', 'decryptions_uploaded', 'decryptions_combined', 'results_released', name='electionstatusenum')
    new_status.drop(op.get_bind(), checkfirst=False)

    # Enum 'NewStatus'
    old_status = sa.Enum('setting_up', 'started', 'ended', 'computing_tally', 'tally_computed', 'decryptions_uploaded', 'decryptions_combined', 'results_released', name='electionstatusenum')
    old_status.create(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###

    with op.batch_alter_table('psifos_election', schema=None) as batch_op:
        batch_op.alter_column('election_status', type_=old_status, existing_type=new_status)
