"""add_count_vote

Revision ID: 16e6279af562
Revises: 89991e18ce13
Create Date: 2023-10-13 01:20:00.951011

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '16e6279af562'
down_revision = '89991e18ce13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_voter', sa.Column('count_vote', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_voter', 'count_vote')
    # ### end Alembic commands ###
