"""removed unique constraint to voter_login_id

Revision ID: 1f453b9318f5
Revises: e5ef0eed35e6
Create Date: 2022-11-24 18:13:04.199168

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '1f453b9318f5'
down_revision = 'e5ef0eed35e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('voter_login_id', table_name='psifos_voter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('voter_login_id', 'psifos_voter', ['voter_login_id'], unique=False)
    # ### end Alembic commands ###
