"""deleted created_by from ElectionLog table

Revision ID: 33e4ccfe2e51
Revises: 43c6bb404a04
Create Date: 2022-11-08 18:30:33.206974

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33e4ccfe2e51'
down_revision = '43c6bb404a04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('election_logs', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election_logs', sa.Column('created_by', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
