"""update trustee models

Revision ID: 3eb9822c3c3e
Revises: 8888e0f12d80
Create Date: 2024-05-30 02:54:59.003544

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3eb9822c3c3e'
down_revision = '8888e0f12d80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psifos_trustee_crypto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('trustee_id', sa.Integer(), nullable=True),
    sa.Column('trustee_election_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('public_key', app.database.custom_fields.PublicKeyField(), nullable=True),
    sa.Column('public_key_hash', sa.String(length=100), nullable=True),
    sa.Column('decryptions', app.database.custom_fields.TrusteeDecryptionsField(), nullable=True),
    sa.Column('certificate', app.database.custom_fields.CertificateField(), nullable=True),
    sa.Column('coefficients', app.database.custom_fields.CoefficientsField(), nullable=True),
    sa.Column('acknowledgements', app.database.custom_fields.AcknowledgementsField(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['psifos_election.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trustee_id'], ['psifos_trustee.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psifos_trustee_crypto_id'), 'psifos_trustee_crypto', ['id'], unique=False)
    op.create_unique_constraint(None, 'psifos_trustee', ['trustee_login_id'])
    op.drop_constraint('psifos_trustee_ibfk_1', 'psifos_trustee', type_='foreignkey')
    op.drop_column('psifos_trustee', 'election_id')
    op.drop_column('psifos_trustee', 'public_key_hash')
    op.drop_column('psifos_trustee', 'current_step')
    op.drop_column('psifos_trustee', 'coefficients')
    op.drop_column('psifos_trustee', 'trustee_id')
    op.drop_column('psifos_trustee', 'decryptions')
    op.drop_column('psifos_trustee', 'acknowledgements')
    op.drop_column('psifos_trustee', 'public_key')
    op.drop_column('psifos_trustee', 'certificate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_trustee', sa.Column('certificate', mysql.LONGTEXT(), nullable=True))
    op.add_column('psifos_trustee', sa.Column('public_key', mysql.LONGTEXT(), nullable=True))
    op.add_column('psifos_trustee', sa.Column('acknowledgements', mysql.LONGTEXT(), nullable=True))
    op.add_column('psifos_trustee', sa.Column('decryptions', mysql.LONGTEXT(), nullable=True))
    op.add_column('psifos_trustee', sa.Column('trustee_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('psifos_trustee', sa.Column('coefficients', mysql.LONGTEXT(), nullable=True))
    op.add_column('psifos_trustee', sa.Column('current_step', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('psifos_trustee', sa.Column('public_key_hash', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('psifos_trustee', sa.Column('election_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('psifos_trustee_ibfk_1', 'psifos_trustee', 'psifos_election', ['election_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'psifos_trustee', type_='unique')
    op.drop_index(op.f('ix_psifos_trustee_crypto_id'), table_name='psifos_trustee_crypto')
    op.drop_table('psifos_trustee_crypto')
    # ### end Alembic commands ###
