"""delete obscure_voter_names

Revision ID: 45d0a669ebf6
Revises: d0ed8e58cae0
Create Date: 2024-12-20 16:34:06.395548

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45d0a669ebf6'
down_revision = 'd0ed8e58cae0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_election', 'obscure_voter_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_election', sa.Column('obscure_voter_names', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
