"""add quorum field

Revision ID: 501d7450da04
Revises: 45d0a669ebf6
Create Date: 2025-07-28 20:32:55.906781

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '501d7450da04'
down_revision = '45d0a669ebf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_election', sa.Column('quorum', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_election', 'quorum')
    # ### end Alembic commands ###
