"""add public vote

Revision ID: 5bd6c609c91a
Revises: 45d0a669ebf6
Create Date: 2025-08-18 19:53:25.304910

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '5bd6c609c91a'
down_revision = '45d0a669ebf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psifos_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('vote', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('cast_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voter_id'], ['psifos_voter.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psifos_vote_id'), 'psifos_vote', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psifos_vote_id'), table_name='psifos_vote')
    op.drop_table('psifos_vote')
    # ### end Alembic commands ###
