"""add login_id_election_id

Revision ID: 620bf0b8c6f5
Revises: 8888e0f12d80
Create Date: 2024-04-14 20:35:04.889871

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '620bf0b8c6f5'
down_revision = '8888e0f12d80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_voter', sa.Column('login_id_election_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###
    connection = op.get_bind()
    result = connection.execute("SELECT id, voter_login_id, election_id FROM psifos_voter")
    for row in result:
        login_id_election_id = f"{row.voter_login_id}_{row.election_id}"
        connection.execute(f"UPDATE psifos_voter SET login_id_election_id = '{login_id_election_id}' WHERE id = {row.id}")
   
    op.create_unique_constraint(None, 'psifos_voter', ['login_id_election_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###y
    op.drop_constraint(None, 'psifos_voter', type_='unique')
    op.drop_column('psifos_voter', 'login_id_election_id')
    # ### end Alembic commands ###
