"""Add excluding groups

Revision ID: 6598764a54f5
Revises: 620bf0b8c6f5
Create Date: 2024-09-30 21:08:18.914347

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6598764a54f5'
down_revision = '620bf0b8c6f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_questions', sa.Column('excluding_groups', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_questions', 'excluding_groups')
    # ### end Alembic commands ###
