"""first migration

Revision ID: 74f1af31ad12
Revises: 
Create Date: 2023-04-18 21:10:02.069227

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '74f1af31ad12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psifos_election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('election_type', sa.Enum('query', 'election', name='electiontypeenum'), nullable=False),
    sa.Column('election_status', sa.Enum('setting_up', 'started', 'ended', 'tally_computed', 'decryptions_uploaded', 'decryptions_combined', 'results_released', name='electionstatusenum'), nullable=True),
    sa.Column('private_p', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_key', app.database.custom_fields.PublicKeyField(), nullable=True),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('questions', app.database.custom_fields.QuestionsField(), nullable=True),
    sa.Column('obscure_voter_names', sa.Boolean(), nullable=False),
    sa.Column('randomize_answer_order', sa.Boolean(), nullable=False),
    sa.Column('normalization', sa.Boolean(), nullable=False),
    sa.Column('max_weight', sa.Integer(), nullable=False),
    sa.Column('total_voters', sa.Integer(), nullable=True),
    sa.Column('total_trustees', sa.Integer(), nullable=True),
    sa.Column('cast_url', sa.String(length=500), nullable=True),
    sa.Column('encrypted_tally', app.database.custom_fields.TallyManagerField(), nullable=True),
    sa.Column('encrypted_tally_hash', sa.Text(), nullable=True),
    sa.Column('decryptions_uploaded', sa.Integer(), nullable=True),
    sa.Column('result', app.database.custom_fields.ElectionResultField(), nullable=True),
    sa.Column('voting_started_at', sa.DateTime(), nullable=True),
    sa.Column('voting_ended_at', sa.DateTime(), nullable=True),
    sa.Column('voters_by_weight_init', sa.Text(), nullable=True),
    sa.Column('voters_by_weight_end', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_psifos_election_id'), 'psifos_election', ['id'], unique=False)
    op.create_table('election_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('log_level', sa.String(length=200), nullable=False),
    sa.Column('event', sa.String(length=200), nullable=False),
    sa.Column('event_params', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['psifos_election.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_election_logs_id'), 'election_logs', ['id'], unique=False)
    op.create_table('psifos_audited_ballot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('raw_vote', sa.Text(), nullable=True),
    sa.Column('vote_hash', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['psifos_election.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psifos_audited_ballot_id'), 'psifos_audited_ballot', ['id'], unique=False)
    op.create_table('psifos_shared_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.Integer(), nullable=False),
    sa.Column('point', app.database.custom_fields.PointField(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['psifos_election.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psifos_shared_point_id'), 'psifos_shared_point', ['id'], unique=False)
    op.create_table('psifos_trustee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('trustee_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trustee_login_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=100), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('public_key', app.database.custom_fields.PublicKeyField(), nullable=True),
    sa.Column('public_key_hash', sa.String(length=100), nullable=True),
    sa.Column('secret_key', sa.Text(), nullable=True),
    sa.Column('pok', sa.Text(), nullable=True),
    sa.Column('decryptions', app.database.custom_fields.TrusteeDecryptionsField(), nullable=True),
    sa.Column('certificate', app.database.custom_fields.CertificateField(), nullable=True),
    sa.Column('coefficients', app.database.custom_fields.CoefficientsField(), nullable=True),
    sa.Column('acknowledgements', app.database.custom_fields.AcknowledgementsField(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['psifos_election.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_psifos_trustee_id'), 'psifos_trustee', ['id'], unique=False)
    op.create_table('psifos_voter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('voter_login_id', sa.String(length=100), nullable=False),
    sa.Column('voter_name', sa.String(length=200), nullable=False),
    sa.Column('voter_weight', sa.Integer(), nullable=False),
    sa.Column('valid_cast_votes', sa.Integer(), nullable=True),
    sa.Column('invalid_cast_votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['psifos_election.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_psifos_voter_id'), 'psifos_voter', ['id'], unique=False)
    op.create_table('psifos_cast_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('vote', app.database.custom_fields.EncryptedVoteField(), nullable=False),
    sa.Column('vote_hash', sa.String(length=500), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('cast_ip', sa.Text(), nullable=False),
    sa.Column('cast_ip_hash', sa.String(length=500), nullable=False),
    sa.Column('cast_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['voter_id'], ['psifos_voter.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voter_id')
    )
    op.create_index(op.f('ix_psifos_cast_vote_id'), 'psifos_cast_vote', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psifos_cast_vote_id'), table_name='psifos_cast_vote')
    op.drop_table('psifos_cast_vote')
    op.drop_index(op.f('ix_psifos_voter_id'), table_name='psifos_voter')
    op.drop_table('psifos_voter')
    op.drop_index(op.f('ix_psifos_trustee_id'), table_name='psifos_trustee')
    op.drop_table('psifos_trustee')
    op.drop_index(op.f('ix_psifos_shared_point_id'), table_name='psifos_shared_point')
    op.drop_table('psifos_shared_point')
    op.drop_index(op.f('ix_psifos_audited_ballot_id'), table_name='psifos_audited_ballot')
    op.drop_table('psifos_audited_ballot')
    op.drop_index(op.f('ix_election_logs_id'), table_name='election_logs')
    op.drop_table('election_logs')
    op.drop_index(op.f('ix_psifos_election_id'), table_name='psifos_election')
    op.drop_table('psifos_election')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
