"""Add questions params

Revision ID: 7a7dabf37829
Revises: 6598764a54f5
Create Date: 2024-10-10 14:17:21.847261

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '7a7dabf37829'
down_revision = '6598764a54f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_questions', sa.Column('options_specifications', sa.JSON(), nullable=True))
    op.add_column('psifos_questions', sa.Column('open_option_max_size', sa.Integer(), nullable=True))
    op.add_column('psifos_questions', sa.Column('total_open_options', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_questions', 'total_open_options')
    op.drop_column('psifos_questions', 'open_option_max_size')
    op.drop_column('psifos_questions', 'options_specifications')
    # ### end Alembic commands ###
