"""election login type

Revision ID: 8888e0f12d80
Revises: 89991e18ce13
Create Date: 2023-12-03 16:26:19.442354

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8888e0f12d80'
down_revision = '89991e18ce13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_election', sa.Column('election_login_type', sa.Enum('close_p', 'open_p', 'semi_close_p', name='electionlogintypeenum'), nullable=True))
    op.drop_column('psifos_election', 'private_p')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_election', sa.Column('private_p', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('psifos_election', 'election_login_type')
    # ### end Alembic commands ###
