"""parametro grouped election

Revision ID: 89991e18ce13
Revises: 35de6acd3bf1
Create Date: 2023-08-24 21:48:20.282240

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89991e18ce13'
down_revision = '35de6acd3bf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_cast_vote', 'vote_group')
    op.add_column('psifos_election', sa.Column('grouped', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_election', 'grouped')
    op.add_column('psifos_cast_vote', sa.Column('vote_group', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
