"""Add secret key

Revision ID: 925d0b34ca55
Revises: 45d0a669ebf6
Create Date: 2025-04-02 14:19:43.410526

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '925d0b34ca55'
down_revision = '45d0a669ebf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psifos_secret_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', mysql.LONGTEXT(), nullable=False),
    sa.Column('proof_of_knowledge', app.database.custom_fields.DLogProofField(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['psifos_election.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psifos_secret_keys_id'), 'psifos_secret_keys', ['id'], unique=False)
    op.add_column('psifos_election', sa.Column('has_psifos_trustees', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_election', 'has_psifos_trustees')
    op.drop_index(op.f('ix_psifos_secret_keys_id'), table_name='psifos_secret_keys')
    op.drop_table('psifos_secret_keys')
    # ### end Alembic commands ###
