"""Add public key table

Revision ID: 96245d935839
Revises: c858304d6e7e
Create Date: 2024-08-06 03:36:05.897727

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96245d935839'
down_revision = 'c858304d6e7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psifos_public_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('y', sa.Text(), nullable=False),
    sa.Column('p', sa.Text(), nullable=False),
    sa.Column('g', sa.Text(), nullable=False),
    sa.Column('q', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psifos_public_keys_id'), 'psifos_public_keys', ['id'], unique=False)
    op.add_column('psifos_election', sa.Column('public_key_id', sa.Integer(), nullable=True, unique=True))
    op.create_foreign_key(None, 'psifos_election', 'psifos_public_keys', ['public_key_id'], ['id'])
    op.drop_column('psifos_election', 'public_key')
    op.add_column('psifos_trustee', sa.Column('public_key_id', sa.Integer(), nullable=True, unique=True))
    op.create_foreign_key(None, 'psifos_trustee', 'psifos_public_keys', ['public_key_id'], ['id'])
    op.drop_column('psifos_trustee', 'public_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_trustee', sa.Column('public_key', mysql.LONGTEXT(), nullable=True))
    op.drop_constraint(None, 'psifos_trustee', type_='foreignkey')
    op.drop_column('psifos_trustee', 'public_key_id')
    op.add_column('psifos_election', sa.Column('public_key', mysql.LONGTEXT(), nullable=True))
    op.drop_constraint(None, 'psifos_election', type_='foreignkey')
    op.drop_column('psifos_election', 'public_key_id')
    op.drop_index(op.f('ix_psifos_public_keys_id'), table_name='psifos_public_keys')
    op.drop_table('psifos_public_keys')
    # ### end Alembic commands ###
