"""add user role

Revision ID: b7ad4c85a420
Revises: 45d0a669ebf6
Create Date: 2025-08-02 19:35:44.834110

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7ad4c85a420'
down_revision = '45d0a669ebf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psifos_election_admins',
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['psifos_election.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('election_id', 'user_id')
    )
    op.add_column('auth_user', sa.Column('role', sa.Enum('admin', 'super_admin', name='userrole'), nullable=False))
    op.drop_constraint('psifos_election_ibfk_1', 'psifos_election', type_='foreignkey')
    op.drop_column('psifos_election', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_election', sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('psifos_election_ibfk_1', 'psifos_election', 'auth_user', ['admin_id'], ['id'])
    op.drop_column('auth_user', 'role')
    op.drop_table('psifos_election_admins')
    # ### end Alembic commands ###
