"""Add questions table and relationships

Revision ID: c858304d6e7e
Revises: 8888e0f12d80
Create Date: 2024-07-22 03:15:15.002715

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c858304d6e7e'
down_revision = '8888e0f12d80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psifos_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('q_num', sa.Integer(), nullable=False),
    sa.Column('q_type', sa.Enum('CLOSED', 'MIXNET', 'STVNC', name='questiontypeenum'), nullable=False),
    sa.Column('q_text', sa.Text(), nullable=False),
    sa.Column('q_description', sa.Text(), nullable=True),
    sa.Column('total_options', sa.Integer(), nullable=False),
    sa.Column('total_closed_options', sa.Integer(), nullable=False),
    sa.Column('closed_options', sa.Text(), nullable=True),
    sa.Column('max_answers', sa.Integer(), nullable=False),
    sa.Column('min_answers', sa.Integer(), nullable=False),
    sa.Column('include_blank_null', sa.String(length=50), nullable=True),
    sa.Column('tally_type', sa.String(length=50), nullable=False),
    sa.Column('group_votes', sa.String(length=50), nullable=True),
    sa.Column('num_of_winners', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['psifos_election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psifos_questions_id'), 'psifos_questions', ['id'], unique=False)
    op.drop_column('psifos_election', 'questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_election', sa.Column('questions', mysql.LONGTEXT(), nullable=True))
    op.drop_index(op.f('ix_psifos_questions_id'), table_name='psifos_questions')
    op.drop_table('psifos_questions')
    # ### end Alembic commands ###
