"""psifos optmized

Revision ID: d0ed8e58cae0
Revises: 0d90832250b7
Create Date: 2024-12-17 14:43:52.256662

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0ed8e58cae0'
down_revision = '0d90832250b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('election_logs', 'created_at',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.DateTime(),
               nullable=True)
    op.add_column('psifos_cast_vote', sa.Column('encrypted_ballot', app.database.custom_fields.EncryptedVoteField(), nullable=False))
    op.add_column('psifos_cast_vote', sa.Column('encrypted_ballot_hash', sa.String(length=500), nullable=False))
    op.drop_column('psifos_cast_vote', 'vote_hash')
    op.drop_column('psifos_cast_vote', 'vote')
    op.add_column('psifos_decryptions_homomorphic', sa.Column('question_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'psifos_decryptions_homomorphic', 'psifos_questions', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('psifos_decryptions_homomorphic', 'q_num')
    op.add_column('psifos_decryptions_mixnet', sa.Column('question_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'psifos_decryptions_mixnet', 'psifos_questions', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('psifos_decryptions_mixnet', 'q_num')
    op.add_column('psifos_election', sa.Column('long_name', sa.String(length=150), nullable=False))
    op.add_column('psifos_election', sa.Column('type', sa.Enum('query', 'election', 'public_vote_election', name='electiontypeenum'), nullable=False))
    op.add_column('psifos_election', sa.Column('status', sa.Enum('setting_up', 'ready_key_generation', 'ready_opening', 'started', 'ended', 'computing_tally', 'tally_computed', 'decryptions_uploaded', 'decryptions_combined', 'results_released', name='electionstatusenum'), nullable=True))
    op.add_column('psifos_election', sa.Column('voters_login_type', sa.Enum('close_p', 'open_p', 'semi_close_p', name='electionlogintypeenum'), nullable=True))
    op.add_column('psifos_election', sa.Column('randomized_options', sa.Boolean(), nullable=False))
    op.add_column('psifos_election', sa.Column('normalized', sa.Boolean(), nullable=False))
    op.add_column('psifos_election', sa.Column('grouped_voters', sa.Boolean(), nullable=False))
    op.alter_column('psifos_election', 'short_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('uuid', table_name='psifos_election')
    op.drop_column('psifos_election', 'name')
    op.drop_column('psifos_election', 'total_trustees')
    op.drop_column('psifos_election', 'voting_ended_at')
    op.drop_column('psifos_election', 'voters_by_weight_init')
    op.drop_column('psifos_election', 'election_login_type')
    op.drop_column('psifos_election', 'randomize_answer_order')
    op.drop_column('psifos_election', 'decryptions_uploaded')
    op.drop_column('psifos_election', 'election_type')
    op.drop_column('psifos_election', 'voting_started_at')
    op.drop_column('psifos_election', 'voters_by_weight_end')
    op.drop_column('psifos_election', 'total_voters')
    op.drop_column('psifos_election', 'election_status')
    op.drop_column('psifos_election', 'grouped')
    op.drop_column('psifos_election', 'uuid')
    op.drop_column('psifos_election', 'normalization')
    op.add_column('psifos_questions', sa.Column('index', sa.Integer(), nullable=False))
    op.add_column('psifos_questions', sa.Column('type', sa.Enum('CLOSED', 'MIXNET', 'STVNC', name='questiontypeenum'), nullable=False))
    op.add_column('psifos_questions', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('psifos_questions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('psifos_questions', sa.Column('formal_options', sa.JSON(), nullable=True))
    op.add_column('psifos_questions', sa.Column('include_informal_options', sa.String(length=50), nullable=True))
    op.add_column('psifos_questions', sa.Column('grouped_options', sa.String(length=50), nullable=True))
    op.add_column('psifos_questions', sa.Column('excluded_options', sa.Boolean(), nullable=True))
    op.drop_column('psifos_questions', 'include_blank_null')
    op.drop_column('psifos_questions', 'q_description')
    op.drop_column('psifos_questions', 'excluding_groups')
    op.drop_column('psifos_questions', 'total_closed_options')
    op.drop_column('psifos_questions', 'closed_options')
    op.drop_column('psifos_questions', 'total_options')
    op.drop_column('psifos_questions', 'q_text')
    op.drop_column('psifos_questions', 'q_type')
    op.drop_column('psifos_questions', 'q_num')
    op.drop_column('psifos_questions', 'group_votes')
    op.add_column('psifos_tallies', sa.Column('question_id', sa.Integer(), nullable=False))
    op.add_column('psifos_tallies', sa.Column('encrypted_tally', mysql.LONGTEXT(), nullable=False))
    op.drop_constraint('psifos_tallies_ibfk_1', 'psifos_tallies', type_='foreignkey')
    op.create_foreign_key(None, 'psifos_tallies', 'psifos_questions', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('psifos_tallies', 'include_blank_null')
    op.drop_column('psifos_tallies', 'num_options')
    op.drop_column('psifos_tallies', 'election_id')
    op.drop_column('psifos_tallies', 'tally')
    op.drop_column('psifos_tallies', 'max_answers')
    op.drop_column('psifos_tallies', 'q_num')
    op.drop_column('psifos_tallies', 'num_of_winners')
    op.add_column('psifos_trustee', sa.Column('username', sa.String(length=100), nullable=False))
    op.drop_index('trustee_login_id', table_name='psifos_trustee')
    op.drop_index('uuid', table_name='psifos_trustee')
    op.create_unique_constraint(None, 'psifos_trustee', ['username'])
    op.drop_column('psifos_trustee', 'trustee_login_id')
    op.drop_column('psifos_trustee', 'uuid')
    op.alter_column('psifos_trustee_crypto', 'current_step',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('config_step', 'secret_key_step', 'certificates_step', 'coefficients_step', 'points_step', 'waiting_decryptions', 'decryptions_sent', name='trusteestepenum'),
               existing_nullable=True)
    op.add_column('psifos_voter', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('psifos_voter', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('psifos_voter', sa.Column('username_election_id', sa.String(length=50), nullable=False))
    op.add_column('psifos_voter', sa.Column('weight_init', sa.Integer(), nullable=False))
    op.add_column('psifos_voter', sa.Column('weight_end', sa.Integer(), nullable=True))
    op.drop_index('login_id_election_id', table_name='psifos_voter')
    op.create_unique_constraint(None, 'psifos_voter', ['username_election_id'])
    op.drop_column('psifos_voter', 'voter_login_id')
    op.drop_column('psifos_voter', 'voter_weight')
    op.drop_column('psifos_voter', 'valid_cast_votes')
    op.drop_column('psifos_voter', 'invalid_cast_votes')
    op.drop_column('psifos_voter', 'login_id_election_id')
    op.drop_column('psifos_voter', 'voter_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_voter', sa.Column('voter_name', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('psifos_voter', sa.Column('login_id_election_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('psifos_voter', sa.Column('invalid_cast_votes', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('psifos_voter', sa.Column('valid_cast_votes', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('psifos_voter', sa.Column('voter_weight', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('psifos_voter', sa.Column('voter_login_id', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'psifos_voter', type_='unique')
    op.create_index('login_id_election_id', 'psifos_voter', ['login_id_election_id'], unique=False)
    op.drop_column('psifos_voter', 'weight_end')
    op.drop_column('psifos_voter', 'weight_init')
    op.drop_column('psifos_voter', 'username_election_id')
    op.drop_column('psifos_voter', 'name')
    op.drop_column('psifos_voter', 'username')
    op.alter_column('psifos_trustee_crypto', 'current_step',
               existing_type=sa.Enum('config_step', 'secret_key_step', 'certificates_step', 'coefficients_step', 'points_step', 'waiting_decryptions', 'decryptions_sent', name='trusteestepenum'),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.add_column('psifos_trustee', sa.Column('uuid', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('psifos_trustee', sa.Column('trustee_login_id', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'psifos_trustee', type_='unique')
    op.create_index('uuid', 'psifos_trustee', ['uuid'], unique=False)
    op.create_index('trustee_login_id', 'psifos_trustee', ['trustee_login_id'], unique=False)
    op.drop_column('psifos_trustee', 'username')
    op.add_column('psifos_tallies', sa.Column('num_of_winners', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('psifos_tallies', sa.Column('q_num', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('psifos_tallies', sa.Column('max_answers', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('psifos_tallies', sa.Column('tally', mysql.LONGTEXT(), nullable=False))
    op.add_column('psifos_tallies', sa.Column('election_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('psifos_tallies', sa.Column('num_options', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('psifos_tallies', sa.Column('include_blank_null', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'psifos_tallies', type_='foreignkey')
    op.create_foreign_key('psifos_tallies_ibfk_1', 'psifos_tallies', 'psifos_election', ['election_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('psifos_tallies', 'encrypted_tally')
    op.drop_column('psifos_tallies', 'question_id')
    op.add_column('psifos_questions', sa.Column('group_votes', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('psifos_questions', sa.Column('q_num', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('psifos_questions', sa.Column('q_type', mysql.ENUM('CLOSED', 'MIXNET', 'STVNC'), nullable=False))
    op.add_column('psifos_questions', sa.Column('q_text', mysql.TEXT(), nullable=False))
    op.add_column('psifos_questions', sa.Column('total_options', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('psifos_questions', sa.Column('closed_options', mysql.TEXT(), nullable=True))
    op.add_column('psifos_questions', sa.Column('total_closed_options', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('psifos_questions', sa.Column('excluding_groups', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('psifos_questions', sa.Column('q_description', mysql.TEXT(), nullable=True))
    op.add_column('psifos_questions', sa.Column('include_blank_null', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('psifos_questions', 'excluded_options')
    op.drop_column('psifos_questions', 'grouped_options')
    op.drop_column('psifos_questions', 'include_informal_options')
    op.drop_column('psifos_questions', 'formal_options')
    op.drop_column('psifos_questions', 'description')
    op.drop_column('psifos_questions', 'title')
    op.drop_column('psifos_questions', 'type')
    op.drop_column('psifos_questions', 'index')
    op.add_column('psifos_election', sa.Column('normalization', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('psifos_election', sa.Column('uuid', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('psifos_election', sa.Column('grouped', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('psifos_election', sa.Column('election_status', mysql.ENUM('setting_up', 'started', 'ended', 'ready_key_generation', 'ready_opening', 'computing_tally', 'tally_computed', 'decryptions_uploaded', 'decryptions_combined', 'results_released'), nullable=True))
    op.add_column('psifos_election', sa.Column('total_voters', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('psifos_election', sa.Column('voters_by_weight_end', mysql.TEXT(), nullable=True))
    op.add_column('psifos_election', sa.Column('voting_started_at', mysql.DATETIME(), nullable=True))
    op.add_column('psifos_election', sa.Column('election_type', mysql.ENUM('query', 'election', 'public_vote_election'), nullable=False))
    op.add_column('psifos_election', sa.Column('decryptions_uploaded', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('psifos_election', sa.Column('randomize_answer_order', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('psifos_election', sa.Column('election_login_type', mysql.ENUM('close_p', 'open_p', 'semi_close_p'), nullable=True))
    op.add_column('psifos_election', sa.Column('voters_by_weight_init', mysql.TEXT(), nullable=True))
    op.add_column('psifos_election', sa.Column('voting_ended_at', mysql.DATETIME(), nullable=True))
    op.add_column('psifos_election', sa.Column('total_trustees', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('psifos_election', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    op.create_index('uuid', 'psifos_election', ['uuid'], unique=False)
    op.alter_column('psifos_election', 'short_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('psifos_election', 'grouped_voters')
    op.drop_column('psifos_election', 'normalized')
    op.drop_column('psifos_election', 'randomized_options')
    op.drop_column('psifos_election', 'voters_login_type')
    op.drop_column('psifos_election', 'status')
    op.drop_column('psifos_election', 'type')
    op.drop_column('psifos_election', 'long_name')
    op.add_column('psifos_decryptions_mixnet', sa.Column('q_num', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'psifos_decryptions_mixnet', type_='foreignkey')
    op.drop_column('psifos_decryptions_mixnet', 'question_id')
    op.add_column('psifos_decryptions_homomorphic', sa.Column('q_num', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'psifos_decryptions_homomorphic', type_='foreignkey')
    op.drop_column('psifos_decryptions_homomorphic', 'question_id')
    op.add_column('psifos_cast_vote', sa.Column('vote', mysql.LONGTEXT(), nullable=False))
    op.add_column('psifos_cast_vote', sa.Column('vote_hash', mysql.VARCHAR(length=500), nullable=False))
    op.drop_column('psifos_cast_vote', 'encrypted_ballot_hash')
    op.drop_column('psifos_cast_vote', 'encrypted_ballot')
    op.alter_column('election_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
