"""modified voter table

Revision ID: e5ef0eed35e6
Revises: 47a29e25a236
Create Date: 2022-11-17 14:48:27.207930

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5ef0eed35e6'
down_revision = '47a29e25a236'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_cast_vote', 'reviewed_at')
    op.create_unique_constraint(None, 'psifos_voter', ['voter_login_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'psifos_voter', type_='unique')
    op.add_column('psifos_cast_vote', sa.Column('reviewed_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
