"""Eliminación de parametros

Revision ID: fadf87014cf2
Revises: 2eb5e33b74f0
Create Date: 2024-08-28 23:19:08.872352

"""
from alembic import op
import sqlalchemy as sa
import app

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fadf87014cf2'
down_revision = '2eb5e33b74f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psifos_cast_vote', 'cast_ip')
    op.drop_column('psifos_cast_vote', 'cast_ip_hash')
    op.drop_index('uuid', table_name='psifos_voter')
    op.drop_column('psifos_voter', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psifos_voter', sa.Column('uuid', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('uuid', 'psifos_voter', ['uuid'], unique=False)
    op.add_column('psifos_cast_vote', sa.Column('cast_ip_hash', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('psifos_cast_vote', sa.Column('cast_ip', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
